CREATE TABLE IF NOT EXISTS ColorVehiculo (
    ColorVehiculoId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Marca (
    MarcaId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Modelo (
    ModeloId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MarcaId INT NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    CONSTRAINT FK_Modelo_Marca FOREIGN KEY (MarcaId) REFERENCES Marca(MarcaId),
    CONSTRAINT UQ_Modelo_MarcaNombre UNIQUE (MarcaId, Nombre)
);

CREATE TABLE IF NOT EXISTS Cliente (
    ClienteId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    PrimerApellido VARCHAR(100) NOT NULL,
    SegundoApellido VARCHAR(100),
    Ci INT NOT NULL,
    CiComplemento VARCHAR(2),
    Telefono INT NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    UsuarioLoginId INT NULL UNIQUE,
    CreadoPor VARCHAR(150) NULL,
    ActualizadoPor VARCHAR(150) NULL,
    EliminadoPor VARCHAR(150) NULL,
    FechaActualizacion TIMESTAMP NULL,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    FechaRegistro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TipoCliente VARCHAR(30) NOT NULL DEFAULT 'Regular'
);

CREATE TABLE IF NOT EXISTS Empleado (
    EmpleadoId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    PrimerApellido VARCHAR(100) NOT NULL,
    SegundoApellido VARCHAR(100),
    Ci INT NOT NULL,
    CiComplemento VARCHAR(2),
    Telefono INT NOT NULL,
    Email VARCHAR(100),
    CreadoPor VARCHAR(150) NULL,
    ActualizadoPor VARCHAR(150) NULL,
    EliminadoPor VARCHAR(150) NULL,
    FechaActualizacion TIMESTAMP NULL,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    FechaContratacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EstadoLaboral VARCHAR(30) NOT NULL DEFAULT 'Activo',
    tipoempleado VARCHAR(50) NOT NULL,
    Especialidad VARCHAR(100) NULL,
    SalarioPorHora DECIMAL(10,2) NULL,
    SalarioMensual DECIMAL(10,2) NULL,
    NivelAcceso VARCHAR(50) NULL
);

CREATE TABLE IF NOT EXISTS Vehiculo (
    VehiculoId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClienteId INT NOT NULL,
    Placa VARCHAR(20) NOT NULL UNIQUE,
    MarcaId INT NOT NULL,
    ModeloId INT NOT NULL,
    ColorVehiculoId INT NOT NULL,
    Anio INT NOT NULL,
    CreadoPor VARCHAR(150) NULL,
    ActualizadoPor VARCHAR(150) NULL,
    EliminadoPor VARCHAR(150) NULL,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    FechaActualizacion TIMESTAMP NULL,
    CONSTRAINT FK_Vehiculo_Cliente FOREIGN KEY (ClienteId) REFERENCES Cliente(ClienteId),
    CONSTRAINT FK_Vehiculo_Marca FOREIGN KEY (MarcaId) REFERENCES Marca(MarcaId),
    CONSTRAINT FK_Vehiculo_Modelo FOREIGN KEY (ModeloId) REFERENCES Modelo(ModeloId),
    CONSTRAINT FK_Vehiculo_Color FOREIGN KEY (ColorVehiculoId) REFERENCES ColorVehiculo(ColorVehiculoId)
);

CREATE TABLE IF NOT EXISTS OrdenTrabajo (
    OrdenTrabajoId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VehiculoId INT NOT NULL,
    FechaIngreso TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FechaEntrega TIMESTAMP NULL,
    EstadoTrabajo VARCHAR(30) NOT NULL,
    EstadoPago VARCHAR(30) NOT NULL,
    EstadoVehiculo VARCHAR(30) NOT NULL,
    Total DECIMAL(10,2) NOT NULL,
    Estado INT NOT NULL DEFAULT 1,
    CreadoPor VARCHAR(150) NULL,
    ActualizadoPor VARCHAR(150) NULL,
    EliminadoPor VARCHAR(150) NULL,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    FechaActualizacion TIMESTAMP NULL,
    CONSTRAINT FK_Orden_Vehiculo FOREIGN KEY (VehiculoId) REFERENCES Vehiculo(VehiculoId)
);

ALTER TABLE IF EXISTS OrdenTrabajo
    ADD COLUMN IF NOT EXISTS Estado INT NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS Producto (
    ProductoId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL UNIQUE,
    Precio DECIMAL(10,2) NOT NULL,
    Stock INT NOT NULL DEFAULT 0,
    CreadoPor VARCHAR(150) NULL,
    ActualizadoPor VARCHAR(150) NULL,
    EliminadoPor VARCHAR(150) NULL,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    FechaActualizacion TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS Servicio (
    ServicioId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(120) NOT NULL UNIQUE,
    Precio DECIMAL(10,2) NOT NULL CHECK (Precio >= 0),
    CreadoPor VARCHAR(150) NULL,
    ActualizadoPor VARCHAR(150) NULL,
    EliminadoPor VARCHAR(150) NULL,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    FechaActualizacion TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS OrdenTrabajoProducto (
    OrdenTrabajoProductoId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrdenTrabajoId INT NOT NULL,
    ProductoId INT NOT NULL,
    Cantidad INT NOT NULL CHECK (Cantidad > 0),
    PrecioUnitario DECIMAL(10,2) NOT NULL CHECK (PrecioUnitario >= 0),
    Subtotal DECIMAL(10,2) NOT NULL CHECK (Subtotal >= 0),
    CreadoPor VARCHAR(150) NULL,
    ActualizadoPor VARCHAR(150) NULL,
    EliminadoPor VARCHAR(150) NULL,
    CONSTRAINT FK_OrdenTrabajoProducto_OrdenTrabajo FOREIGN KEY (OrdenTrabajoId) REFERENCES OrdenTrabajo(OrdenTrabajoId) ON DELETE CASCADE,
    CONSTRAINT FK_OrdenTrabajoProducto_Producto FOREIGN KEY (ProductoId) REFERENCES Producto(ProductoId)
);

CREATE INDEX IF NOT EXISTS IX_OrdenTrabajoProducto_OrdenTrabajoId ON OrdenTrabajoProducto (OrdenTrabajoId);
CREATE INDEX IF NOT EXISTS IX_OrdenTrabajoProducto_ProductoId ON OrdenTrabajoProducto (ProductoId);

CREATE TABLE IF NOT EXISTS OrdenTrabajoServicio (
    OrdenTrabajoServicioId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrdenTrabajoId INT NOT NULL,
    ServicioId INT NOT NULL,
    Cantidad INT NOT NULL CHECK (Cantidad > 0),
    PrecioUnitario DECIMAL(10,2) NOT NULL CHECK (PrecioUnitario >= 0),
    Subtotal DECIMAL(10,2) NOT NULL CHECK (Subtotal >= 0),
    CreadoPor VARCHAR(150) NULL,
    ActualizadoPor VARCHAR(150) NULL,
    EliminadoPor VARCHAR(150) NULL,
    CONSTRAINT FK_OrdenTrabajoServicio_OrdenTrabajo FOREIGN KEY (OrdenTrabajoId) REFERENCES OrdenTrabajo(OrdenTrabajoId) ON DELETE CASCADE,
    CONSTRAINT FK_OrdenTrabajoServicio_Servicio FOREIGN KEY (ServicioId) REFERENCES Servicio(ServicioId)
);

CREATE INDEX IF NOT EXISTS IX_OrdenTrabajoServicio_OrdenTrabajoId ON OrdenTrabajoServicio (OrdenTrabajoId);
CREATE INDEX IF NOT EXISTS IX_OrdenTrabajoServicio_ServicioId ON OrdenTrabajoServicio (ServicioId);

CREATE TABLE IF NOT EXISTS OrdenTrabajoMecanico (
    OrdenTrabajoId INT NOT NULL,
    MecanicoId INT NOT NULL,
    FechaAsignacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CreadoPor VARCHAR(150) NULL,
    ActualizadoPor VARCHAR(150) NULL,
    EliminadoPor VARCHAR(150) NULL,
    CONSTRAINT PK_OrdenTrabajoMecanico PRIMARY KEY (OrdenTrabajoId, MecanicoId),
    CONSTRAINT FK_OrdenTrabajoMecanico_OrdenTrabajo FOREIGN KEY (OrdenTrabajoId) REFERENCES OrdenTrabajo(OrdenTrabajoId) ON DELETE CASCADE,
    CONSTRAINT FK_OrdenTrabajoMecanico_Mecanico FOREIGN KEY (MecanicoId) REFERENCES Empleado(EmpleadoId) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IX_OrdenTrabajoMecanico_MecanicoId ON OrdenTrabajoMecanico (MecanicoId);

CREATE TABLE IF NOT EXISTS OrdenTrabajoFoto (
    OrdenTrabajoFotoId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrdenTrabajoId     INT NOT NULL,
    Datos              BYTEA NOT NULL,
    ContentType        VARCHAR(100) NOT NULL,
    NombreArchivo      VARCHAR(255) NOT NULL,
    CreadoPor          VARCHAR(150) NULL,
    ActualizadoPor     VARCHAR(150) NULL,
    EliminadoPor       VARCHAR(150) NULL,
    FechaRegistro      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_OrdenTrabajoFoto_OrdenTrabajo FOREIGN KEY (OrdenTrabajoId) REFERENCES OrdenTrabajo(OrdenTrabajoId) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IX_OrdenTrabajoFoto_OrdenTrabajoId ON OrdenTrabajoFoto (OrdenTrabajoId);

CREATE TABLE IF NOT EXISTS UsuarioLogin (
    UsuarioLoginId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmpleadoId INT NULL,
    ClienteId INT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    UltimoAcceso TIMESTAMP NULL,
    FechaActualizacion TIMESTAMP NULL,
    CreadoPor VARCHAR(150) NULL,
    ActualizadoPor VARCHAR(150) NULL,
    InactivadoPor VARCHAR(150) NULL,
    Activo BOOLEAN NOT NULL DEFAULT TRUE,
    RequiereCambioPassword BOOLEAN NOT NULL DEFAULT TRUE,
    EsCliente BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS IX_Producto_Nombre ON Producto (Nombre);

CREATE TABLE IF NOT EXISTS audit_logs (
    id              SERIAL PRIMARY KEY,
    tabla_afectada  VARCHAR(100) NOT NULL,
    registro_id     INT NOT NULL,
    accion          VARCHAR(50)  NOT NULL,
    realizado_por   VARCHAR(150),
    fecha_hora      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IX_audit_logs_tabla ON audit_logs (tabla_afectada, registro_id);


INSERT INTO ColorVehiculo (Nombre) VALUES
('Blanco'), ('Negro'), ('Plata'), ('Gris'), ('Rojo'),
('Azul'), ('Verde'), ('Amarillo'), ('Naranja'), ('Café'),
('Dorado'), ('Beige'), ('Celeste'), ('Guindo'), ('Perla')
ON CONFLICT (Nombre) DO NOTHING;

INSERT INTO Marca (Nombre) VALUES
('Toyota'), ('Nissan'), ('Suzuki'), ('Honda'), ('Hyundai'),
('Kia'), ('Chevrolet'), ('Ford'), ('Volkswagen'), ('Mazda'),
('Mitsubishi'), ('Peugeot'), ('Renault'), ('BMW'), ('Mercedes-Benz'),
('Audi'), ('Jeep')
ON CONFLICT (Nombre) DO NOTHING;

INSERT INTO Modelo (MarcaId, Nombre) VALUES
-- 1. Toyota
(1, 'Corolla'), (1, 'Hilux'), (1, 'RAV4'), (1, 'Yaris'), (1, 'Land Cruiser'), (1, 'Tacoma'), (1, '4Runner'), (1, 'Coaster'),

-- 2. Nissan
(2, 'Sentra'), (2, 'Frontier'), (2, 'Kicks'), (2, 'Versa'), (2, 'X-Trail'), (2, 'Patrol'), (2, 'March'), (2, 'Navara'),

-- 3. Suzuki
(3, 'Swift'), (3, 'Vitara'), (3, 'Jimny'), (3, 'Grand Vitara'), (3, 'Alto'), (3, 'Baleno'), (3, 'Celerio'), (3, 'Ertiga'),

-- 4. Honda
(4, 'Civic'), (4, 'CR-V'), (4, 'HR-V'), (4, 'Accord'), (4, 'Fit'), (4, 'Pilot'),

-- 5. Hyundai
(5, 'Tucson'), (5, 'Elantra'), (5, 'Santa Fe'), (5, 'Accent'), (5, 'Creta'), (5, 'i10'), (5, 'H-1'),

-- 6. Kia
(6, 'Sportage'), (6, 'Rio'), (6, 'Sorento'), (6, 'Picanto'), (6, 'Cerato'), (6, 'Seltos'), (6, 'Carnival'),

-- 7. Chevrolet
(7, 'Spark'), (7, 'Tracker'), (7, 'Silverado'), (7, 'Cruze'), (7, 'Onix'), (7, 'Captiva'), (7, 'Camaro'),

-- 8. Ford
(8, 'F-150'), (8, 'Ranger'), (8, 'Explorer'), (8, 'Escape'), (8, 'Mustang'), (8, 'Fiesta'), (8, 'EcoSport'),

-- 9. Volkswagen
(9, 'Gol'), (9, 'Jetta'), (9, 'Tiguan'), (9, 'Amarok'), (9, 'Polo'), (9, 'Golf'), (9, 'Saveiro'), (9, 'Touareg'),

-- 10. Mazda
(10, 'Mazda3'), (10, 'CX-5'), (10, 'Mazda2'), (10, 'CX-3'), (10, 'BT-50'),

-- 11. Mitsubishi
(11, 'L200'), (11, 'Outlander'), (11, 'Montero'), (11, 'ASX'), (11, 'Lancer'), (11, 'Pajero'),

-- 12. Peugeot
(12, '208'), (12, '3008'), (12, '2008'), (12, '308'), (12, 'Partner'),

-- 13. Renault
(13, 'Duster'), (13, 'Logan'), (13, 'Sandero'), (13, 'Stepway'), (13, 'Kwid'), (13, 'Kangoo'),

-- 14. BMW
(14, 'X3'), (14, 'X5'), (14, 'Serie 3'), (14, 'Serie 5'), (14, 'X1'),

-- 15. Mercedes-Benz
(15, 'Clase C'), (15, 'Clase E'), (15, 'GLE'), (15, 'GLC'), (15, 'Clase A'), (15, 'Sprinter'),

-- 16. Audi
(16, 'A3'), (16, 'A4'), (16, 'Q5'), (16, 'Q3'), (16, 'Q7'),

-- 17. Jeep
(17, 'Grand Cherokee'), (17, 'Compass'), (17, 'Renegade'), (17, 'Wrangler')
ON CONFLICT ON CONSTRAINT uq_modelo_marcanombre DO NOTHING;

-- Datos por defecto para Productos y Servicios
INSERT INTO producto (nombre, precio, stock) VALUES
-- Productos (refacciones)
('Aceite de Motor 5W-30', 150.00, 20),
('Filtro de Aceite', 80.00, 30),
('Filtro de Aire', 75.00, 25),
('Filtro de Combustible', 95.00, 20),
('Pastillas de Freno Delanteras', 350.00, 15),
('Pastillas de Freno Traseras', 280.00, 15),
('Discos de Freno', 450.00, 10),
('Batería 12V 60Ah', 1200.00, 8),
('Batería 12V 70Ah', 1500.00, 5),
('Liquido de Frenos DOT4', 120.00, 20),
('Refrigerante', 100.00, 25),
('Limpiaparabrisas', 60.00, 30),
('Bujías', 200.00, 20),
('Correa de Distribucción', 800.00, 5),
('Cadena de Tracción', 650.00, 8),
('Amortiguadores Delanteros', 1200.00, 6),
('Amortiguadores Traseros', 1000.00, 6),
('Rotulas', 350.00, 12),
('Terminales de Dirección', 280.00, 12),
('Mangueras de Frenos', 400.00, 8)
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO servicio (nombre, precio, isdeleted, fechaactualizacion, creadopor) VALUES
('Cambio de Aceite', 350.00, FALSE, NULL, 'SYSTEM_SEED'),
('Cambio de Filtros', 250.00, FALSE, NULL, 'SYSTEM_SEED'),
('Alineación de Ruedas', 300.00, FALSE, NULL, 'SYSTEM_SEED'),
('Balanceo de Ruedas', 200.00, FALSE, NULL, 'SYSTEM_SEED'),
('Cambio de Pastillas', 400.00, FALSE, NULL, 'SYSTEM_SEED'),
('Cambio de Discos', 600.00, FALSE, NULL, 'SYSTEM_SEED'),
('Cambio de Batería', 150.00, FALSE, NULL, 'SYSTEM_SEED'),
('Lavado de Motor', 500.00, FALSE, NULL, 'SYSTEM_SEED'),
('Lavado de Carrocería', 150.00, FALSE, NULL, 'SYSTEM_SEED'),
('Cambio de Llanta', 100.00, FALSE, NULL, 'SYSTEM_SEED'),
('Diagnóstico Computarizado', 300.00, FALSE, NULL, 'SYSTEM_SEED'),
('Cambio de Empaques', 1500.00, FALSE, NULL, 'SYSTEM_SEED'),
('Reparación de Motor', 8000.00, FALSE, NULL, 'SYSTEM_SEED'),
('Pintura General', 15000.00, FALSE, NULL, 'SYSTEM_SEED'),
('Pulido y Encerado', 400.00, FALSE, NULL, 'SYSTEM_SEED')
ON CONFLICT (nombre) DO NOTHING;

-- ─────────────────────────────────────────────
-- Sistema de Roles
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS Rol (
    RolId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL UNIQUE,
    Descripcion VARCHAR(200) NULL
);

-- Agregar columna rolid si no existe (migración segura)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'usuariologin' AND column_name = 'rolid') THEN
        ALTER TABLE UsuarioLogin ADD COLUMN rolid INT REFERENCES Rol(RolId);
    END IF;
END $$;

-- Seed de roles por defecto
INSERT INTO Rol (nombre, descripcion) VALUES
('Gerente', 'Acceso a usuarios, gestion de roles y reportes'),
('Administrador', 'Acceso completo al sistema'),
('Mecanico', 'Acceso a órdenes de trabajo'),
('Cliente', 'Acceso limitado a sus propios datos')
ON CONFLICT (nombre) DO NOTHING;
