-- ============================================================
-- setup_database_completo.sql
-- Migracion idempotente: aplica todos los cambios faltantes
-- sobre la BD TallerMecanico (PostgreSQL 17, puerto 5433)
-- Se puede ejecutar multiples veces sin errores.
-- ============================================================

-- --------------------------------------------------------
-- 1. Columnas faltantes en usuariologin
-- --------------------------------------------------------
ALTER TABLE usuariologin
    ADD COLUMN IF NOT EXISTS username VARCHAR(100) NULL;

ALTER TABLE usuariologin
    ADD COLUMN IF NOT EXISTS usuario_creacion VARCHAR(150) NULL;

ALTER TABLE usuariologin
    ADD COLUMN IF NOT EXISTS fecha_creacion TIMESTAMP NULL;

ALTER TABLE usuariologin
    ADD COLUMN IF NOT EXISTS usuario_modificacion VARCHAR(150) NULL;

ALTER TABLE usuariologin
    ADD COLUMN IF NOT EXISTS fecha_modificacion TIMESTAMP NULL;

-- --------------------------------------------------------
-- 2. Tabla audit_logs  (requerida por UsuarioLoginRepository)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada  VARCHAR(100) NOT NULL,
    registro_id     INT NOT NULL,
    accion          VARCHAR(20)  NOT NULL,   -- INSERT / UPDATE / DELETE
    realizado_por   VARCHAR(150) NOT NULL,
    fecha_hora      TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS IX_audit_logs_tabla_registro
    ON audit_logs (tabla_afectada, registro_id);

-- --------------------------------------------------------
-- 3. Tabla ordentrabajocatalogo  (requerida por OrdenTrabajoService)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS ordentrabajocatalogo (
    ordentrabajocatalogoid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordentrabajoid         INT NOT NULL,
    productoid             INT NOT NULL,
    cantidadutilizada      INT NOT NULL DEFAULT 1,
    preciounitario         DECIMAL(10,2) NOT NULL DEFAULT 0,
    fecharegistro          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creadopor              VARCHAR(150) NULL,
    CONSTRAINT FK_OTC_OrdenTrabajo FOREIGN KEY (ordentrabajoid)
        REFERENCES ordentrabajo (ordentrabajoid) ON DELETE CASCADE,
    CONSTRAINT FK_OTC_Producto FOREIGN KEY (productoid)
        REFERENCES producto (productoid)
);

CREATE INDEX IF NOT EXISTS IX_OTC_OrdenTrabajoId
    ON ordentrabajocatalogo (ordentrabajoid);

-- --------------------------------------------------------
-- 4. Usuario admin por defecto para pruebas
--    (solo inserta si no existe ya un usuario con ese email)
-- --------------------------------------------------------
DO $$
DECLARE
    v_empleado_id INT;
    v_login_id    INT;
BEGIN
    -- Insertar empleado admin si no existe
    IF NOT EXISTS (SELECT 1 FROM empleado WHERE email = 'admin@taller.com') THEN
        INSERT INTO empleado (
            nombre, primerapellido, ci, telefono, email,
            tipoempleado, especialidad, nivelacceso,
            estadolaboral, isdeleted
        )
        VALUES (
            'Admin', 'Sistema', 12345678, 70000000, 'admin@taller.com',
            'Administrador', 'Gestion', 'Admin',
            'Activo', FALSE
        )
        RETURNING empleadoid INTO v_empleado_id;
    ELSE
        SELECT empleadoid INTO v_empleado_id
        FROM empleado WHERE email = 'admin@taller.com';
    END IF;

    -- Insertar login admin si no existe
    IF NOT EXISTS (SELECT 1 FROM usuariologin WHERE email = 'admin@taller.com') THEN
        INSERT INTO usuariologin (
            empleadoid, clienteid, email, username, passwordhash,
            activo, requierecambiopassword, escliente,
            usuario_creacion, fecha_creacion
        )
        VALUES (
            v_empleado_id,
            NULL,
            'admin@taller.com',
            'admin',
            -- BCrypt hash para 'Admin123!' (cost=11)
            '$2a$11$K7kMJzlTJeECaO5uTWbEMOcR.N0kVCkB3mCsQCH4QvEpJL3F5K8si',
            TRUE,
            FALSE,
            FALSE,
            'SYSTEM_SEED',
            NOW()
        );
    END IF;
END $$;

-- --------------------------------------------------------
-- 5. Rellenar username en registros existentes que lo tengan NULL
-- --------------------------------------------------------
UPDATE usuariologin
SET username = SPLIT_PART(email, '@', 1)
WHERE username IS NULL;

-- --------------------------------------------------------
-- Fin de la migracion
-- --------------------------------------------------------
SELECT 'Migracion completada exitosamente.' AS resultado;
